// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBayrrjyhUpzwbh_CDIYRyxm3ML_BpEQpg',
    appId: '1:543560135896:web:106cfc10b82f1b741f93ad',
    messagingSenderId: '543560135896',
    projectId: 'free-time-planner',
    authDomain: 'free-time-planner.firebaseapp.com',
    storageBucket: 'free-time-planner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr1sGy2Qdu6eFojEiUmZQRQJRVkT2JuaQ',
    appId: '1:543560135896:android:8b912c21cda63c881f93ad',
    messagingSenderId: '543560135896',
    projectId: 'free-time-planner',
    storageBucket: 'free-time-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTJpR51i7WopKM-QreGkoktgyLIChrxc',
    appId: '1:543560135896:ios:6dce944c862ed1771f93ad',
    messagingSenderId: '543560135896',
    projectId: 'free-time-planner',
    storageBucket: 'free-time-planner.appspot.com',
    iosClientId: '543560135896-uvui3b8n476bo0ulu8hsbjscab3jbtb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeTimePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTJpR51i7WopKM-QreGkoktgyLIChrxc',
    appId: '1:543560135896:ios:6dce944c862ed1771f93ad',
    messagingSenderId: '543560135896',
    projectId: 'free-time-planner',
    storageBucket: 'free-time-planner.appspot.com',
    iosClientId: '543560135896-uvui3b8n476bo0ulu8hsbjscab3jbtb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeTimePlanner',
  );
}
